del "./*.h"
copy "..\..\..\src\data\pokemon\species_info\gen_1_families.h" "./"
copy "..\..\..\src\data\pokemon\species_info\gen_2_families.h" "./"
copy "..\..\..\src\data\pokemon\species_info\gen_3_families.h" "./"
copy "..\..\..\src\data\pokemon\species_info\gen_4_families.h" "./"
copy "..\..\..\src\data\pokemon\species_info\gen_5_families.h" "./"
copy "..\..\..\src\data\pokemon\species_info\gen_6_families.h" "./"
copy "..\..\..\src\data\pokemon\species_info\gen_7_families.h" "./"
copy "..\..\..\src\data\pokemon\species_info\gen_8_families.h" "./"
copy "..\..\..\src\data\pokemon\species_info\gen_9_families.h" "./"
py generate_species_tables.py